import type { WatermarkPreset } from '../types/watermark';

export const WATERMARK_PRESETS: WatermarkPreset[] = [
  {
    id: 'confidential-diagonal',
    name: 'Confidential (Red Diagonal)',
    description: 'Prominent diagonal warning stamp for sensitive documents',
    badge: 'Popular',
    config: {
      type: 'text',
      positionMode: 'grid',
      gridPosition: 'center',
      text: {
        text: 'CONFIDENTIAL',
        fontFamily: 'Helvetica, Arial, sans-serif',
        fontSize: 48,
        fontSizeMode: 'percent',
        fontSizePercent: 12,
        color: '#dc2626',
        opacity: 0.35,
        rotation: -35,
        bold: true,
        italic: false,
        underline: false,
        stroke: true,
        strokeColor: '#991b1b',
        strokeWidth: 2,
        shadow: false,
        shadowColor: '#000000',
        shadowBlur: 4,
        background: false,
        bgColor: '#fee2e2',
        bgOpacity: 0.5,
        bgPadding: 12,
        bgRadius: 8,
      },
    },
  },
  {
    id: 'draft-subtle',
    name: 'Draft (Subtle)',
    description: 'Semi-transparent large draft watermark in the center',
    badge: 'Document',
    config: {
      type: 'text',
      positionMode: 'grid',
      gridPosition: 'center',
      text: {
        text: 'DRAFT - DO NOT COPY',
        fontFamily: 'Helvetica, Arial, sans-serif',
        fontSize: 42,
        fontSizeMode: 'percent',
        fontSizePercent: 9,
        color: '#64748b',
        opacity: 0.28,
        rotation: -45,
        bold: true,
        italic: false,
        underline: false,
        stroke: false,
        strokeColor: '#000000',
        strokeWidth: 1,
        shadow: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        background: false,
        bgColor: '#ffffff',
        bgOpacity: 0,
        bgPadding: 0,
        bgRadius: 0,
      },
    },
  },
  {
    id: 'copyright-corner',
    name: 'Copyright Notice',
    description: 'Subtle clean copyright marker in bottom-right corner',
    badge: 'Photo',
    config: {
      type: 'text',
      positionMode: 'grid',
      gridPosition: 'bottom-right',
      text: {
        text: '© 2026 All Rights Reserved',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 24,
        fontSizeMode: 'percent',
        fontSizePercent: 3.5,
        color: '#ffffff',
        opacity: 0.8,
        rotation: 0,
        bold: true,
        italic: false,
        underline: false,
        stroke: false,
        strokeColor: '#000000',
        strokeWidth: 1,
        shadow: true,
        shadowColor: '#000000',
        shadowBlur: 6,
        background: true,
        bgColor: '#000000',
        bgOpacity: 0.45,
        bgPadding: 8,
        bgRadius: 6,
      },
    },
  },
  {
    id: 'repeated-tile',
    name: 'Security Tile Pattern',
    description: 'Tiled repeating watermark across the entire image / page',
    badge: 'High Security',
    config: {
      type: 'text',
      positionMode: 'tile',
      tileSettings: {
        gapX: 180,
        gapY: 120,
        diagonalOffset: true,
      },
      text: {
        text: 'WATERMARK • DO NOT REPRODUCE',
        fontFamily: 'Helvetica, Arial, sans-serif',
        fontSize: 22,
        fontSizeMode: 'percent',
        fontSizePercent: 3.5,
        color: '#94a3b8',
        opacity: 0.22,
        rotation: -30,
        bold: true,
        italic: false,
        underline: false,
        stroke: false,
        strokeColor: '#000000',
        strokeWidth: 1,
        shadow: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        background: false,
        bgColor: '#ffffff',
        bgOpacity: 0,
        bgPadding: 0,
        bgRadius: 0,
      },
    },
  },
  {
    id: 'photographer-signature',
    name: 'Artist / Photographer Signature',
    description: 'Elegant script style watermark for photography portfolios',
    badge: 'Creative',
    config: {
      type: 'text',
      positionMode: 'grid',
      gridPosition: 'bottom-center',
      text: {
        text: 'Captured by Studio Pro',
        fontFamily: 'Georgia, serif',
        fontSize: 28,
        fontSizeMode: 'percent',
        fontSizePercent: 4.5,
        color: '#f8fafc',
        opacity: 0.85,
        rotation: 0,
        bold: false,
        italic: true,
        underline: false,
        stroke: false,
        strokeColor: '#000000',
        strokeWidth: 1,
        shadow: true,
        shadowColor: '#000000',
        shadowBlur: 8,
        background: false,
        bgColor: '#000000',
        bgOpacity: 0,
        bgPadding: 0,
        bgRadius: 0,
      },
    },
  },
  {
    id: 'sample-center',
    name: 'Sample Overlay',
    description: 'High visibility preview sample watermark',
    badge: 'Proofing',
    config: {
      type: 'text',
      positionMode: 'grid',
      gridPosition: 'center',
      text: {
        text: 'SAMPLE',
        fontFamily: 'Impact, Arial Black, sans-serif',
        fontSize: 72,
        fontSizeMode: 'percent',
        fontSizePercent: 16,
        color: '#ffffff',
        opacity: 0.4,
        rotation: -25,
        bold: true,
        italic: false,
        underline: false,
        stroke: true,
        strokeColor: '#000000',
        strokeWidth: 3,
        shadow: true,
        shadowColor: '#000000',
        shadowBlur: 10,
        background: false,
        bgColor: '#000000',
        bgOpacity: 0,
        bgPadding: 0,
        bgRadius: 0,
      },
    },
  },
];
